version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: SUISP_MinIO
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: suispadmin
      MINIO_ROOT_PASSWORD: suispadmin67
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 1;
    
      mc alias set localminio http://minio:9000 suispadmin suispadmin67;
      mc mb -p localminio/suispbucket || true;
      mc admin user add localminio suispapp suispappsecret;
      mc admin policy create localminio suispapp-policy /tmp/policy.json;
      mc admin policy attach localminio suispapp-policy --user suispapp;

      exit 0;
      "
    volumes:
      - ./policy.json:/tmp/policy.json:ro

volumes:
  minio_data: